name: CustomCommands
main: com.retrohaven.customcommands.CustomCommands
version: 1.0
api-version: 1.7.3
author: Lilly E (retrorandom)

commands:
  meow:
    description: Meows in chat
    usage: /meow
    permission: customcommands.meow
  hug:
    description: Hugs a player
    usage: /hug <player>
    permission: customcommands.hug
  wave:
    description: Waves at a player
    usage: /wave <player>
    permission: customcommands.wave
  silly:
    description: Be silly
    usage: /silly
    permission: customcommands.silly
  pet:
    description: Pet a player
    usage: /pet <player>
    permission: customcommands.pet
  milk:
    description: Milk another player and receive a milk bucket
    usage: /milk <player>
    permission: customcommands.milk

permissions:
  customcommands.meow:
    description: Allows use of /meow
    default: false
  customcommands.hug:
    description: Allows use of /hug
    default: false
  customcommands.wave:
    description: Allows use of /wave
    default: false
  customcommands.silly:
    description: Allows use of /silly
    default: false
  customcommands.pet:
    description: Allows use of /pet
    default: false
  customcommands.milk:
    description: Allows use of /milk
    default: false
