name: CustomCommands
main: com.retrohaven.customcommands.CustomCommands
version: 1.0
api-version: 1.7.3
author: RetroHaven
commands:
  meow:
    description: Meows in chat
    usage: /meow
    permission: customcommands.meow
  hug:
    description: Hugs a player
    usage: /hug <player>
    permission: customcommands.hug
  wave:
    description: Waves at a player
    usage: /wave <player>
    permission: customcommands.wave
  silly:
    description: Broadcasts a silly message
    usage: /silly
    permission: customcommands.silly
permissions:
  customcommands.meow:
    description: Allows use of /meow
    default: true
  customcommands.hug:
    description: Allows use of /hug
    default: op
  customcommands.wave:
    description: Allows use of /wave
    default: true
  customcommands.silly:
    description: Allows use of /silly
    default: true
